# tasks file for docker_install
---
- name: Update apt and install dependencies
  ansible.builtin.apt:
    update_cache: true
    name: "{{ docker_apt_dependencies }}"
    state: present

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: "{{ docker_gpg_url }}"
    state: present

- name: Set up the stable repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_repo }}"
    state: present

- name: Update apt and install Docker Engine
  ansible.builtin.apt:
    update_cache: true
    name: "{{ docker_packages }}"

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
